---
name: grafana

x-environment: &environment
  env_file:
    - .env
  environment:
    - PUID=${PUID} # default user id $USERid, defined in .env
    - PGID=${PGID} # default group id, defined in .env
    - TZ=${TZ} # timezone, defined in .env

x-restart: &restart
  restart: unless-stopped

x-time-volume: &timevolume
  volumes:
    - /etc/localtime:/etc/localtime:ro

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "2m"


volumes:
  grafana:

services:
  # The Grafana dashboarding server.
  grafana:
    container_name: grafana
    image: grafana/grafana:11.2.0
    <<: [*environment, *restart, *timevolume, *logging]
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph traceqlSearch traceQLStreaming correlations metricsSummary traceqlEditor traceToMetrics traceToProfiles datatrails
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app,grafana-exploretraces-app
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true

  loki:
    container_name: loki
    image: grafana/loki:3.2.0
    command: ["--pattern-ingester.enabled=true", "-config.file=/etc/loki/loki.yaml"]
    <<: [*environment, *restart, *timevolume, *logging]
    ports:
      - "3100:3100"
    volumes:
      - "./loki/loki.yaml:/etc/loki/loki.yaml"

  mimir:
    container_name: mimir
    image: grafana/mimir:2.13.0
    command: ["-ingester.native-histograms-ingestion-enabled=true", "-config.file=/etc/mimir.yaml"]
    <<: [*environment, *restart, *timevolume, *logging]
    ports:
      - "9009:9009"
    volumes:
      - "./mimir/mimir.yaml:/etc/mimir.yaml"
